#!/home/codespace/.python/current/bin/python
print ("---------------------Prueba para introducir un nombre de usuario-------------------")

nombredeusuario=input("Introduce el nombre de usuario/email de la plataforma: ")

arroba=nombredeusuario.count('@')
punto=nombredeusuario.count('.')

print(arroba,punto)

while(arroba!=1 or nombredeusuario.rfind('@')==(len(nombredeusuario)-1) or nombredeusuario.find('@')==0 or punto!=1):
    print("Usuario incorrecto")
    nombredeusuario=input("Introduce el nombre de usuario/email de la plataforma: ")

print("Usuario correcto")
